version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "3030:3030"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432'
  kulki:
    image: kulki
    restart: always
    ports:
      - '8080'
    depends_on:
      - db
    env_file:
      - docker.env
