version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
#  kulki:
#    image: kulki
#    restart: always
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#    env_file:
#      - docker.env
